profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<slug:slug>/edit/", views.update, name="update"),
    path("<slug:slug>/password/", views.change_password, name="change_password"),
    path("<slug:slug>/delete/", views.delete, name="delete"),
    path("<slug:slug>/", views.profile, name="user"),
]

project/urls.py
from django.urls import path

from . import views

app_name = "project"


urlpatterns = [
    path("", views.ProjectListView.as_view(), name="list"),
    path("tag=<str:tag>/", views.ProjectTagView.as_view(), name="tag"),
    path("submit/", views.ProjectCreateView.as_view(), name="submit"),
]

templates/about.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}About{% endblock title %}

{% block content %}
<div class="flex flex-col items-center justify-center mx-6 pt-4">
  <div class="text-3xl font-light leading-8 mb-6">
    List of awesome personal side projects.
  </div>
  <div class="text-gray-700">© Side Project List</div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta content="en" name="language">

  <meta name="msvalidate.01" content="" />

  <!-- SEO -->
  <meta class="swiftype" name="title" data-type="string" content="">
  <meta class="swiftype" name="description" data-type="string" content="">
  <meta name="keywords" content="">
  <meta name="robots" content="nofollow">

  {% block stylesheet %}{% endblock stylesheet%}

  <link rel="stylesheet" href="{% static 'css/tailwind-output.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script> -->

  <title>Side Project List: {% block title %}{% endblock title %}</title>
</head>

<!-- <body class="text-gray-800 text-lg" style="background-color: #f0f2f5"> -->

<body class="text-gray-800 text-lg">
  {% include './navbar.html' %}

  <!-- 
    django  levels:
    DEBUG, INFO, SUCCESS, WARNING, ERROR
    -->

  {% if messages %}
  <div class="z-50 text-center flex flex-col">
    {% for message in messages %}
    <div class="
    {% if message.tags == 'success' %}  bg-green-100 border-green-400 text-green-800
    {% elif message.tags == 'error' %} bg-red-100 border-red-400 text-red-800
    {% elif message.tags == 'warning' %} bg-yellow-100 border-yellow-400 text-yellow-800
    {% elif message.tags == 'info' %} bg-blue-100 border-blue-400 text-blue-800
    {% else %} bg-blue-100 border-blue-400 text-blue-800
    {% endif %}
     border px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">{{ message.tags }} {{ message }}</span>
      <span class="absolute top-0 bottom-0 right-0 px-4 py-3 text-gray-600 hover:text-gray-800 ">
        <svg id="message{{ forloop.counter }}" onclick="hideThisMessage(this.id)" class="fill-current w-5 h-5"
          role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
          <path
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" />
        </svg>
      </span>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <div class="mb-6">
    {% block content %}
    <!-- <h4><span class="label label-primary">block from base.html</span></h4> -->
    {% endblock content %}
  </div>

  <!-- this button must come before 'scriptjs' -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js"></script>
  {% block javascript %}{% endblock javascript %}
  <!-- javascript block must come after all the other scripts-->


  <script>
    // hide selected django message
    function hideThisMessage(id) {
      console.log(id);
      document.querySelector(`#${id}`).parentElement.parentElement.style.display = "none";
    }

  </script>

</body>

</html>

templates/base_error.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6 mt-3">

    <div class="card card-pricing">
      <div class="card-body text-center">
        <h3 class="card-title">
          {% block error_title %}
          {% endblock error_title %}
        </h3>
        <p class="card-text">
          {% block error_message %}
          {% endblock error_message %}
        </p>
      </div>
    </div>

  </div>
</div>
{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
{% endblock javascript %}

{% block stylesheet %}
<meta name="robots" content="noindex">
{% endblock stylesheet%}

{% block content %}
<div id="dashboard" class="text-sm">
  <div class="text-2xl font-semibold">Users ({{ user_count }})</div>
  <div class="">
    <div class="signupcount-linechart-container" style="height: 180px;">
      <signupcount-linechart :name='signupCountName' :labels='signupDateLabels' :series='signupCountSeries'>
      </signupcount-linechart>
    </div>
  </div>

  <div class="flex flex-col items-center justify-center text-center w-1/2 mt-4 ">

    <button @click="saveInfoForAll"
      class="bg-pink-600 hover:bg-pink-500 text-white px-4 py-2 mt-2 rounded-lg tracking-wide">
      Save screenshot / twitter_info (avatar, follower) for all (async)
    </button>

    <button @click="saveScreenshotForAll"
      class="bg-yellow-600 hover:bg-yellow-500 text-white px-4 py-2 mt-2 rounded-lg tracking-wide">
      Save screenshot for all (async)
    </button>

    <button @click="saveTwitterInfoForAll"
      class="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 mt-2 rounded-lg tracking-wide">
      Save twitter_info (avatar, follower) for all (async)
    </button>

    <a href="{% url 'generate-json' %}"
      class="bg-green-600 hover:bg-green-500 text-white px-4 py-2 mt-2 rounded-lg tracking-wide">
      Generate json (sync)
    </a>

    <div class="mt-6">
      <div class="text-lg font-semibold">
        Users without screenshot ({{users_without_screenshot|length}})
      </div>
      {% if users_without_screenshot %}
      {% for user in users_without_screenshot %}
      <p>
        {{user.maker_fullname}}
      </p>
      {% endfor %}
      {% endif %}
    </div>

    <div class="mt-6">
      <div class="text-lg font-semibold">
        Projects ({{projects|length}})
      </div>
      {% if projects %}
      {% for project in projects %}
      <div class="flex items-center mt-1">
        {{ project.id }}
        {{ project.maker_fullname }}


        {% if project.is_screenshot_not_saved %}
        <div class="bg-red-600 text-white rounded-lg ml-2 px-2">
          screenshot: x
        </div>
        {% endif %}

        {% if project.is_avatar_not_saved %}
        <div class="bg-red-600 text-white rounded-lg ml-2 px-2">
          avatar: x
        </div>
        {% endif %}


        <a href="{% url 'save-info-for-each' project.id %}" class="{% if project.is_screenshot_not_saved or project.is_twitter_info_not_saved %}
          bg-indigo-600 
          {% else %}
          bg-gray-600 
          {% endif %}
          text-white px-2 py-1 ml-2 rounded">Fetch screenshot (sync)</a>
      </div>
      {% endfor %}
      {% endif %}
    </div>

  </div>

</div>


{% endblock content %}

templates/error.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h3>error.__cause__</h3>
<p>
	{{ error }}
</p>
<p>{{ message }}</p>
{% endblock content %}

templates/home.html
{% extends './base.html' %}
{% load tz %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block title %}{{ block.super }}{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}
{% block content %}
{{ block.super }}


<div class="row justify-content-center">
  <h1>home</h1>
</div>

{% endblock content %}

templates/navbar.html
{% load static %}

<nav id="navbar">
  <header class="bg-white sm:flex sm:justify-between border-b border-gray-300 shadow-sm">
    <div class="flex items-center justify-between pl-3 py-2 h-16">

      <div class="sm:hidden" style="touch-action: manipulation;">
        <button @click="isMenuOpen = !isMenuOpen" type="button" class="block focus:outline-none">
          <svg class="h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <!-- Hamburger menu -->
            <path v-if="!isMenuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16" />
            <!-- menu X -->
            <path v-if="isMenuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex items-center">
        <a href="{% url 'project:list' %}" class=" px-1 py-1 font-bold text-lg">
          Side Project List
        </a>
      </div>
      <div class="sm:hidden mr-3" style="touch-action: manipulation;">
        {% if not request.user.is_authenticated %}
        <a href="{% url 'account_login' %}" class="block px-3 py-2 text-center rounded-lg  hover:bg-gray-200">
          Log in</a>
        {% else %}
        <a href="{% url 'profiles:user' request.user.slug %}" class="">
          <!-- <div class="w-10 h-10 text-xl text-center align-middle rounded-full bg-indigo-600 text-white p-1 hover:bg-indigo-700"> -->
          <div class="hover:text-gray-800 font-semibold">
            <!-- user-circle -->
            <svg class="h-10 w-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
                clipRule="evenodd" />
            </svg>
          </div>
        </a>
        {% endif %}
      </div>

    </div>
    <div :class="isMenuOpen ? 'block' : 'hidden'" class="px-2 py-2 sm:flex sm:items-center">
      {% if request.user.is_superuser %}
      <a href="{% url 'admin:index' %}" target="_blank" rel="noopener noreferrer"
        class="block px-3 py-2 ml-2 sm:text-white sm:bg-purple-600 text-center sm:rounded-lg sm:border-none border-t border-gray-300">
        Admin
      </a>
      {% endif %}

      {% if request.user.is_staff %}
      <a href="{% url 'dashboard' %}"
        class="block px-3 py-2 ml-2 sm:text-white sm:bg-purple-600 text-center sm:rounded-lg sm:border-none border-t border-gray-300">
        Dashboard
      </a>
      {% endif %}

      {% if request.user.is_authenticated %}
      <a href="{% url 'profiles:user' request.user.slug %}"
        class="flex items-center justify-center px-3 py-2 ml-2 text-center sm:rounded-lg sm:border-none border-t border-gray-300 hover:bg-gray-200">
        Hi, <span class="font-semibold">
          {{ user.firstname_or_username }}
        </span>
      </a>
      <a href="{% url 'account_logout' %}"
        class="block px-3 py-2 ml-2 text-center sm:rounded-lg sm:border-none border-t border-gray-300 hover:bg-gray-200 sm:mt-0">
        Log out</a>
      {% else %}
      <a href="{% url 'account_signup' %}"
        class="block px-3 py-2 ml-2 font-semibold text-center sm:rounded-lg border-t border-gray-300 hover:bg-gray-200 sm:border-2 sm:border-indigo-400">
        Sign up</a>
      <a href="{% url 'account_login' %}"
        class="block px-3 py-2 ml-2 text-center sm:rounded-lg sm:border-none border-t border-gray-300 hover:bg-gray-200 sm:mt-0">
        Log in</a>
      {% endif %}

      <a href="{% url 'project:submit' %}"
        class="block px-3 py-2 ml-2 text-center sm:rounded-lg sm:border-none border-t border-gray-300 hover:bg-gray-200">
        Submit
      </a>
      <a href="{% url 'about' %}"
        class="block px-3 py-2 ml-2 text-center sm:rounded-lg sm:border-none border-t border-gray-300 hover:bg-gray-200 sm:mt-0">
        About</a>


    </div>
  </header>
</nav>

{% block javascript %}
<script src="{% static 'js/navbar.js' %}"></script>
{% endblock javascript %}