profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<slug:slug>/edit/", views.update, name="update"),
    path("<slug:slug>/password/", views.change_password, name="change_password"),
    path("<slug:slug>/delete/", views.delete, name="delete"),
    path("<slug:slug>/", views.profile, name="user"),
]

project/urls.py
from django.urls import path

from . import views

app_name = "project"


urlpatterns = [
    path("", views.ProjectListView.as_view(), name="list"),
    path("tag=<str:tag>/", views.ProjectTagView.as_view(), name="tag"),
    path("submit/", views.ProjectCreateView.as_view(), name="submit"),
]

profiles/models.py
from allauth.account.adapter import DefaultAccountAdapter
from allauth.exceptions import ImmediateHttpResponse
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from allauth.socialaccount.models import SocialAccount
from allauth.utils import email_address_exists
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.forms import ValidationError, forms
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.text import slugify
from sideprojectlist.models import TimeStampedModel


class CustomAccountAdapter(DefaultAccountAdapter):
    error_messages = DefaultAccountAdapter.error_messages
    error_messages["username_taken"] = "This username is already taken"
    error_messages["email_taken"] = "This email is already taken"

    # def clean_username(self, username):
    #     if len(username) > settings.ACCOUNT_USERNAME_MAX_LENGTH:
    #         raise ValidationError("Username is too long")
    #     return DefaultAccountAdapter.clean_username(
    #         self, username
    #     )  # For other default validations


class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    error_messages = DefaultSocialAccountAdapter.error_messages
    error_messages[
        "email_taken"
    ] = "%s: An account already exists with this email."  # <- needs "%s"

    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)
        user.username = user.email.split("@")[0]

        # If user tries to login with socialaccount for the first time without signing up before,
        # it will automatically signup and login the user
        # This behaviour is unexpected, and prevented here
        # TODO Below check should only be done when in login page, but not in signup page...
        # if not user.is_signedup_with_socialauth():
        #     messages.warning(request, f"You're not signed up with '{user.email}'")
        #     raise ImmediateHttpResponse(redirect("/accounts/login/"))

        return user


class User(AbstractUser):
    # TODO make sure slug length/max_length is consistent with username
    slug = models.SlugField(max_length=100, allow_unicode=True, unique=True)
    bio = models.CharField(max_length=280, null=True, blank=True)
    website = models.URLField(max_length=200)

    class Meta:
        ordering = ["-date_joined"]

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("profiles:user", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        # if not self.id:
        # Newly created
        self.slug = slugify(self.username)
        self.email = BaseUserManager.normalize_email(self.email)
        super().save(*args, **kwargs)

    @property
    def fullname(self):
        # ? Should I use strip()?
        return f"{self.first_name} {self.last_name}"

    @property
    def initial(self):
        # ? Should I use strip()?
        initial = ""
        if len(self.first_name) > 0:
            initial = self.first_name[0]
        if len(self.last_name) > 0:
            initial += self.last_name[0]

        if not (self.first_name or self.last_name):
            initial = self.username[0]
        return initial

    @property
    def firstname_or_username(self):
        if self.first_name:
            return self.first_name
        return self.username

    def all_users_except_superuser(self):
        return User.objects.exclude(is_superuser=True).order_by("-date_joined")

    def all_users_except_me(self):
        return User.objects.exclude(id=self.id)

    def is_signedup_with_socialauth(self):
        try:
            social_user_id = SocialAccount.objects.get(user_id=self.id).user_id
            if social_user_id:
                return True
            return False
        except:
            return False

    def is_loggedin_with_socialauth(self):
        return self.is_authenticated and self.is_signedup_with_socialauth()


class Follow:
    pass

profiles/forms.py
import re

from django import forms
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

from allauth.account.forms import LoginForm, ResetPasswordForm, SignupForm
from allauth.account.utils import filter_users_by_email
from allauth.socialaccount.models import SocialAccount

# from crispy_forms.helper import FormHelper
# from uploads.core.models import Document
# from django.contrib.auth.forms import UserCreationForm
from .models import User

USERNAME_HELP_TEXT = "Alphanumeric characters (a-z, 0-9) and underscore (_)"


def profile_username_validation(username):
    if re.findall(r"[^a-zA-Z0-9_]", username):
        raise forms.ValidationError(f"{USERNAME_HELP_TEXT} only")


class UserCreationForm(SignupForm):
    """
    Custom class is used primarily to change username validation to limit special characters
    """

    # Copied from allauth.account.forms.py and changed
    # TODO catch exception: settings.ACCOUNT_USERNAME_MIN_LENGTH not defined
    email = forms.EmailField(
        label="Email",
        required=settings.ACCOUNT_EMAIL_REQUIRED,
        widget=forms.TextInput(
            attrs={"type": "email", "size": "30", "placeholder": "Email"}
        ),
        help_text="",
    )

    username = forms.CharField(
        label="Username",
        min_length=settings.ACCOUNT_USERNAME_MIN_LENGTH,
        widget=forms.TextInput(attrs={"placeholder": "Username"}),
        help_text="",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].label = "Email"
        self.fields["email"].placeholder = "Email"

    def clean_username(self):
        super().clean_username()
        username = self.cleaned_data.get("username")
        profile_username_validation(username)
        return username


class LoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["login"].label = "Email"
        # TODO How to change placeholder for email
        # Try to override allauth.account.forms.AddEmailForm?
        # self.fields["login"].placeholder = "Email"  # <-- not working

    def clean_login(self):
        email = self.cleaned_data["login"]
        try:
            user = User.objects.get(email=email)
            if user.is_signedup_with_socialauth():
                social = SocialAccount.objects.get(user_id=user.id)
                raise forms.ValidationError(
                    f"You are signed up with {social.provider.capitalize()}. Please use 'Log in with {social.provider.capitalize()}'"
                )
        except ObjectDoesNotExist:
            pass

        return super().clean_login()


class UserUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True
        # self.fields.keyOrder = []
        self.fields["username"].help_text = USERNAME_HELP_TEXT

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "bio", "website"]
        widgets = {"bio": forms.Textarea(attrs={"rows": 2})}

    def clean_username(self):
        username = self.cleaned_data.get("username")
        profile_username_validation(username)
        return username


class UserResetPasswordForm(ResetPasswordForm):
    def clean_email(self):

        email = self.cleaned_data["email"]
        users = filter_users_by_email(email)
        if len(users) == 1:
            try:
                social = SocialAccount.objects.get(user_id=users[0].id)
                if social:
                    raise forms.ValidationError(
                        f"You are signed up with {social.provider.capitalize()}. You are not supposed to reset password on this site."
                    )
            except ObjectDoesNotExist:
                pass

        return super().clean_email()

profiles/views.py
from allauth.socialaccount.models import SocialAccount
from core.utils import staff_check
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import UserUpdateForm
from .models import User


@login_required
def profile(request, slug):
    template = "profiles/profile.html"
    user = get_object_or_404(User, slug=slug)

    # superuser shouldn't be visible to anyone else
    superuser = get_object_or_404(User, is_superuser=True)
    if slug == superuser.slug and request.user.slug != slug:
        raise Http404

    context = {"u": user}
    return render(request, template, context)


@login_required
def delete(request, slug):
    template = "profiles/profile_confirm_delete.html"
    user = get_object_or_404(User, id=request.user.id)
    context = {"u": user}

    if request.method == "POST":
        user.delete()
        messages.success(request, f"Account deleted")
        return HttpResponseRedirect(reverse("home"))

    return render(request, template, context)


# https://simpleisbetterthancomplex.com/tips/2016/08/04/django-tip-9-password-change-form.html
@login_required
def change_password(request, slug):
    # Users with socialauth login is not supposed to change password inside app
    if request.user.is_loggedin_with_socialauth():
        provider = SocialAccount.objects.get(user_id=request.user.id).provider
        msg = f"You are not supposed to change password in this website as you are logged in with {provider}."
        raise PermissionDenied(msg)

    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password changed")
            return redirect(reverse("profiles:user", args=[user.slug]))
        else:
            print("Password form not valid")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "profiles/profile_change_password.html", {"form": form})


@login_required
def update(request, slug):
    if request.method == "POST":
        user = request.user
        form = UserUpdateForm(request.POST, instance=request.user)

        if form.is_valid():
            changed_list = []
            if form.has_changed():
                # messages.success(request, f'Profile updated: {form.changed_data}')
                changed_list = form.changed_data

            # msg = "Profile updated: " + ", ".join(changed_list)
            # messages.success(request, msg)
            # TODO "Profile updated" vs "Profile edited"
            messages.success(request, "Profile updated")
            try:
                form.save()
            except IntegrityError:
                messages.error(request, "Profile update failed...")
            return HttpResponseRedirect(reverse("profiles:user", args=[user.slug]))
        else:
            print("Update form not valid")

    else:
        form = UserUpdateForm(instance=request.user)

    context = {"form": form}
    template = "profiles/profile_update.html"
    return render(request, template, context)

templates/profiles/profile.html
{% extends 'base.html' %}
{% load static %}
{% load profile_extra %}

{% block title %}
{{ u.get_username }}
{% if u.get_full_name %}
({{ u.get_full_name }})
{% endif %}
{% endblock title %}

{% block content %}
<div class="">
	<div class="">
		<h3 class="text-2xl font-semibold text-center">Profile</h3>

		{% profile_card u %}

		{% if u == request.user %}
		<div class="text-center mt-2">
			<a href="{% url 'profiles:update' request.user.slug %}"
				class="bg-indigo-600 hover:bg-indigo-500 text-white font-medium px-4 py-2 mt-2 rounded tracking-wide">Edit
				profile</a>
		</div>
		{% endif %}
	</div>
</div>
{% endblock content %}

templates/profiles/profile_card.html
{% load static %}

<div class="">
  <div class="">

    <div class="">
      <span class="">{{ u.initial }}</span>
    </div>

    <div class="">
      <span class="">{{ u.get_full_name }}</span>
      <span class="">({{ u.get_username|truncatechars:18 }})</span>

      {% if u.bio %}
      <div class="">
        <div>Bio: {{ u.bio }}</div>
      </div>
      {% endif %}

      {% if u.website %}
      <div class="">
        <div>{{ u.website }}</div>
      </div>
      {% endif %}
    </div>

  </div>
</div>

templates/profiles/profile_change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Change password{% endblock %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="">
  <div class="">
    <div>
      <h3 class="text-center">Change password</h3>
      <form action="{% url 'profiles:change_password' request.user.slug %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        {% if form %}
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Change password</button>
        </div>
        {% endif %}

      </form>
    </div>

  </div>
</div>

{% endblock content %}

templates/profiles/profile_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete{% endblock title %}

{% block content %}
<div class="">
  <div class="">
    <form method="post">
      {% csrf_token %}
      <div class="">
        <div class="">
          <h5 class="">We're sorry to see you go</h5>
          <hr>
          <p class="">Hi {{ u }},</p>
          <p class="">Are you sure you want to delete your account?</p>
          <div class="">
            <a href="{{request.META.HTTP_REFERER}}" class="">Cancel</a>
            <input type="submit" value="Delete" class="">
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

templates/profiles/profile_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update{% endblock %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="">
	<div class="">
		<div>
			<h3 class="text-center">Edit profile</h3>
			<form action="{% url 'profiles:update' request.user.slug %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}

				<div class="">
					{% if not user.is_loggedin_with_socialauth %}
					<a href="{% url 'profiles:change_password' request.user.slug %}">Change password</a>
					{% endif %}
				</div>

				{% if form %}
				<div class="text-center my-4">
					<button type="submit" class="" id="profileUpdateBtn">Save changes</button>
				</div>
				{% endif %}

				<div class="">
					<a href=" {% url 'profiles:delete' request.user.slug %}" class="text-danger">Delete account</a>
				</div>

			</form>
		</div>

	</div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/utils.js' %}"></script>
<script>
	const profileUpdateBtn = document.querySelector("#profileUpdateBtn")
	profileUpdateBtn.addEventListener('click', function () {
		if (this.form && isFormHtml5Valid(this.form, 'input')) {
			this.disabled = true
			this.textContent = "Saving..."
			this.form.submit()
		}
	})
</script>
{% endblock javascript %}