project/urls.py
from django.urls import path

from . import views

app_name = "project"


urlpatterns = [
    path("", views.ProjectListView.as_view(), name="list"),
    path("tag=<str:tag>/", views.ProjectTagView.as_view(), name="tag"),
    path("submit/", views.ProjectCreateView.as_view(), name="submit"),
]

project/models.py
import os
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify
from sideprojectlist.models import TimeStampedModel
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from .tasks import save_info

# https://stackoverflow.com/questions/9522759/imagefield-overwrite-image-file-with-same-name
class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


class Project(TimeStampedModel):
    slug = models.SlugField(max_length=100, allow_unicode=True)
    link = models.URLField(max_length=200, unique=True)
    maker_fullname = models.CharField(max_length=100)
    twitter_handle = models.CharField(max_length=20, null=True, blank=True, unique=True)
    twitter_followers_count = models.PositiveIntegerField(default=0)
    github_handle = models.CharField(max_length=20, null=True, blank=True, unique=True)
    is_approved = models.BooleanField(default=True)
    screenshot = models.ImageField(upload_to="screenshot/", null=True, blank=True, storage=OverwriteStorage)
    maker_avatar = models.ImageField(upload_to="avatar/", null=True, blank=True, storage=OverwriteStorage)
    tags = models.CharField(max_length=256, null=True, blank=True, help_text="Comma separated strings")
    cloudinary_screenshot_url = models.URLField(max_length=200, null=True, blank=True)
    cloudinary_maker_avatar_url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.maker_fullname}"

    def get_absolute_url(self):
        return reverse("project:list")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.maker_fullname)
        super().save(*args, **kwargs)

    class Meta:
        unique_together = [["link", "maker_fullname"]]

    @property
    def is_screenshot_not_saved(self):
        if self.screenshot and self.cloudinary_screenshot_url:
            return False
        return True

    @property
    def is_avatar_not_saved(self):
        if not self.twitter_handle:
            return False
        if self.maker_avatar and self.cloudinary_maker_avatar_url:
            return False
        return True

    @property
    def is_twitter_info_not_saved(self):
        return self.is_avatar_not_saved

    @property
    def tags_in_list(self):
        try:
            temp_tags = self.tags.strip().rstrip(",").split(",")
            return [tag.strip().lower() for tag in temp_tags]
        except AttributeError:
            return ""

    @property
    def like_count(self):
        return Like.objects.filter(project=self.id).count()

    @classmethod
    def screenshot_not_saved_count(cls):
        return Project.objects.filter(screenshot=None).count()

    @classmethod
    def users_without_screenshot(cls):
        return Project.objects.filter(cloudinary_screenshot_url__isnull=True)


# TODO check permission
@receiver(post_save, sender=Project)
# def project_post_save(sender, instance, created, **kwargs):
def project_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    if not created:
        return

    save_info.apply_async(
        args=(instance.id,),
        # link=success_callback.s(request.user.id),
        link=None,
        link_error=None,
    )


class Like(models.Model):
    project = models.ForeignKey(Project, related_name="liked_project", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="liked_user", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return f"{self.project.maker_fullname} liked by {self.user}"

project/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.html import format_html
from django.views.generic import (
    CreateView,
    ListView,
)

# from .forms import DistrictCreateForm, DistrictPasswordChangeForm, DistrictUpdateForm
from .models import Project


class ProjectTagView(ListView):
    model = Project
    template_name = "project/project_list.html"
    context_object_name = "projects"

    def get_queryset(self):
        return Project.objects.filter(is_approved=True).filter(tags__icontains=self.kwargs["tag"]).order_by("-created")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag_selected"] = self.kwargs["tag"]
        return context


class ProjectListView(ListView):
    model = Project
    template_name = "project/project_list.html"
    context_object_name = "projects"

    def get_queryset(self):
        return Project.objects.filter(is_approved=True).order_by("-created")


class ProjectCreateView(CreateView):
    model = Project
    fields = [
        "link",
        "maker_fullname",
        "twitter_handle",
        "github_handle",
        "tags",
    ]
    # form_class = ProjectCreateForm
    template_name = "project/project_create.html"

    # def form_valid(self, form):
    #     form.instance.submitted_by = self.request.user
    #     try:
    #         success_url = super().form_valid(form)
    #         form.instance.save()
    #         return success_url
    #     except IntegrityError as e:
    #         # TODO
    #         messages.error(self.request, f"Something went wrong: {e}")
    #         return HttpResponseRedirect(reverse("project:submit"))

templates/project/project_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block title %}Submit{% endblock %}

{% block content %}
<div class="flex items-center justify-center">
  <div class="block">
    <div class="block text-2xl font-semibold">Submit</div>
    <div class="block text-gray-700 mb-3">Requires a review</div>

    <form action="{% url 'project:submit' %}" method="POST">
      {% csrf_token %}
      {{ form|crispy }}

      {% if form %}
      <div class="text-center">
        <button type="submit"
          class="bg-indigo-600 hover:bg-indigo-500 text-white font-medium px-4 py-2 rounded tracking-wide"
          id="addBtn">Submit a request</button>
      </div>
      {% endif %}
    </form>
  </div>

</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/utils.js' %}"></script>
<script>
  // Prevent double clicking add button and sending multiple form submits
  const addBtn = document.querySelector("#addBtn")
  addBtn.addEventListener('click', function () {
    if (this.form && isFormHtml5Valid(this.form, 'input,select')) {
      this.disabled = true
      this.classList.remove('bg-indigo-600', 'hover:bg-indigo-500')
      this.classList.add('bg-gray-400')
      this.textContent = "Submitting..."
      this.form.submit()
    }
  })
</script>
{% endblock javascript %}

templates/project/project_list.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}

{% block title %}List of awesome side projects{% endblock title %}

{% block content %}
<div id="project-list" class="mx-2">
  <div class="flex items-center justify-between pt-4 pb-2 mx-4">
    <div class="flex items-center justify-start text-2xl font-semibold">
      {% if tag_selected %}
      <div class="">
        <a href="{% url 'project:list' %}" class="text-indigo-700 hover:text-indigo-700 hover:underline">
          Projects
        </a>
        / {{ tag_selected }} ({{ projects|length }})
      </div>
      {% else %}
      <div>
        Projects ({{ projects|length }})
      </div>
      {% endif %}

    </div>

    <div class="text-sm font-semibold text-gray-600">
      Sort by...
    </div>
  </div>

  <div class="flex flex-wrap">
    {% if projects %}
    {% for project in projects %}
    <div class="flex flex-col items-center justify-start sm:w-1/2 md:w-1/3">
      <div class="border border-gray-400 mx-3 my-3 bg-white rounded-xl shadow-lg">
        <div class="border-b border-gray-400 ">
          <a href="{{ project.link }}" target="_blank" rel="noopener noreferrer"
            class="flex flex-col items-center justify-center text-indigo-700 hover:text-indigo-700 hover:underline">
            {% if project.cloudinary_screenshot_url %}
            <img class="w-full rounded-t-xl" src="{{ project.cloudinary_screenshot_url }}" alt="screenshot">
            {% else %}
            {{ project.link }}
            {% endif %}
          </a>
        </div>

        <div class="px-4 py-3">
          <div class="flex items-center justify-start flex-wrap">
            <div class="flex-shrink-0">
              {% if project.cloudinary_maker_avatar_url %}
              <img class="w-8 rounded-full mr-1" src="{{ project.cloudinary_maker_avatar_url }}" alt="twitter avatar">
              {% else %}
              <!-- user-circle -->
              <svg class="w-8 mr-1 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                fill="currentColor">
                <path fillRule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
                  clipRule="evenodd" />
              </svg>
              {% endif %}
            </div>


            <div class="text-2xl font-bold">
              {{ project.maker_fullname }}
            </div>

            {% if project.twitter_handle %}
            <div class="ml-1 flex">
              <a href="https://twitter.com/{{ project.twitter_handle }}" target="_blank" rel="noopener noreferrer"
                class="flex-wrap text-indigo-700 hover:text-indigo-700 hover:underline">
                @{{ project.twitter_handle|truncatechars:"18" }}
              </a>
            </div>
            {% endif %}

          </div>

          <div class="mt-2 mb-3">
            <div class="flex flex-wrap items-center mt-4">
              {% for tag in project.tags_in_list %}
              <a href="{% url 'project:tag' tag %}" class="block bg-gray-300 rounded-md px-2 mr-2 mt-2 hover:underline">
                {{ tag }}
              </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="text-2xl pt-4 mx-4">
      No projects...
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}